apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: receipt-service
requires:
- configs:
  - e2e-tests
  path: ../../../skaffold-e2e.yaml
- configs:
  - ledger-db
  path: ../ledger-db/skaffold.yaml
build:
  artifacts:
  - image: receipt-service
    context: ../../../
    docker:
      dockerfile: src/ledger/receipt-service/Dockerfile
  tagPolicy:
    sha256: {}
test:
  - image: receipt-service # unit tests
    context: ../../../src/ledger/receipt-service
    custom:
      - command: go test ./...
        timeoutSeconds: 1200
  - image: receipt-service # code coverage
    context: ../../../src/ledger/receipt-service
    custom:
      - command: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out
        timeoutSeconds: 1200
deploy:
  kubectl: {}
profiles:
- name: development
  activation:
  - command: dev
  manifests:
    kustomize:
      paths:
      - k8s/overlays/development
      - ../../../iac/acm-multienv-cicd-anthos-autopilot/overlays/development
- name: staging
  manifests:
    kustomize:
      paths:
      - k8s/overlays/staging
- name: production
  manifests:
    kustomize:
      paths:
      - k8s/overlays/production
- name: production-fwi
  manifests:
    kustomize:
      paths:
      - k8s/overlays/production-fwi
